buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
		maven { url 'https://maven.fabricmc.net' }
		maven { url 'https://repo.sleeping.town' }
	}
	dependencies {
		classpath "agency.highlysuspect:voldeloom:2.4"
	}
}

apply plugin: 'java'
apply plugin: "agency.highlysuspect.voldeloom"

java.toolchain.languageVersion = JavaLanguageVersion.of(11)
compileJava.options.release.set(6)

def forgeVersion = '1.4.7-6.6.2.534'
def minecraftVersion = "1.4.7"
def lombokVersion = "1.18.36"

archivesBaseName = "ChiselRetro"
version = "beta0.9+bugfixes"
group = "net.fybertech"

repositories {
	mavenLocal()
	maven { url 'https://maven.fabricmc.net/' }
	maven { url 'https://maven.minecraftforge.net/' }
	maven { url 'https://repo.spongepowered.org/maven' }
	maven { url 'https://repo.sleeping.town' }
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraftVersion}"
	forge "net.minecraftforge:forge:${forgeVersion}:universal@zip"
	mappings "net.minecraftforge:forge:${forgeVersion}:src@zip"
	implementation "com.google.guava:guava:12.0.1"

	compileOnly "org.projectlombok:lombok:${lombokVersion}"
	annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}

jar {
	destinationDir file("build/tmp")
}

processResources {
	inputs.property "version", project.version

	filesMatching("mcmod.info") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile) {
	options.encoding = "UTF-8"
}
